// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value | comment
    // 1 | open | /h |  | 
    driver.get("https://classroom.google.com/h");
    // 2 | setWindowSize | 1050x964 |  | 
    driver.manage().window().setSize(new Dimension(1050, 964));
    // 3 | mouseOver | css=.gHz6xd:nth-child(4) > .SZ0kZe > div:nth-child(1) .XuQwKc |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".gHz6xd:nth-child(4) > .SZ0kZe > div:nth-child(1) .XuQwKc"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | verifyText | css=.oOGT6 |  | 
    assertThat(driver.findElement(By.cssSelector(".oOGT6")).getText(), is("undefined"));
    // 5 | click | css=.DShyMc-MTA2OTk2ODk5MzRa .R4EiSb > .onkcGd |  | 
    driver.findElement(By.cssSelector(".DShyMc-MTA2OTk2ODk5MzRa .R4EiSb > .onkcGd")).click();
    // 6 | mouseOut | css=.gHz6xd:nth-child(4) > .SZ0kZe > div:nth-child(1) .XuQwKc |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void strimGooglClassroom() {
    // Test name: StrimGooglClassroom
    // Step # | name | target | value | comment
    // 1 | open | /c/MTg0ODM1NTQyODJa |  | 
    driver.get("https://classroom.google.com/c/MTg0ODM1NTQyODJa");
    // 2 | setWindowSize | 1080*600 |  | 
    driver.manage().window().setSize(new Dimension(1080*600, undefined));
    // 3 | click | css=.dbEQNc:nth-child(3) .u2KWf |  | 
    driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .u2KWf")).click();
    // 4 | click | css=.dbEQNc:nth-child(3) .jgNzTd |  | 
    driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .jgNzTd")).click();
    // 5 | click | css=.dbEQNc:nth-child(3) .jgNzTd |  | 
    driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .jgNzTd")).click();
    // 6 | doubleClick | css=.dbEQNc:nth-child(3) .jgNzTd |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .jgNzTd"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 7 | doubleClick | css=.dbEQNc:nth-child(3) .jgNzTd |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .jgNzTd"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 8 | click | css=.dbEQNc:nth-child(3) .jgNzTd |  | 
    driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .jgNzTd")).click();
    // 9 | click | css=.dbEQNc:nth-child(3) .u2KWf |  | 
    driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .u2KWf")).click();
    // 10 | click | css=.dbEQNc:nth-child(3) .jgNzTd |  | 
    driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .jgNzTd")).click();
    // 11 | storeText | css=.dbEQNc:nth-child(3) .KCofJf | text\n | 
    vars.put("text\n", driver.findElement(By.cssSelector(".dbEQNc:nth-child(3) .KCofJf")).getText());
  }
}
